travis:
  secure:
    BINSTAR_TOKEN: sXjmE848k+24Q5XMW9vNjGEd6c3dfdPVsAp2DcByffZ0N4xxx9K3jVlKHCW09M6npugKhG0JGAx/J7lDqAsYhgfei0zYzV0SUAvd6F31cGUnkJ8rf+JAmQnuptabJoL742Vnl5DvlkSrKxH5Nz3+oTW++qS00TTOrwnrdAQi5q4DmTFmvR4w6zaprVrPQUJBHFXO22E6OGRtJ9iz/Rq4MJAR3bFAM6rsLfxyInQlUPBTGEcRNP2QlglCpUc0HdmT6/Ir9bbdj9hNYBH76TxEmiQ4oMC/Q4+ysC4sORjHBXxZRv+siYIVQTXdsBBi6JG0DYgoMHFgE6SwjUY2+LQpll+ZlqFp7kFkQHaboI6ud7FxxRrwFwVTwSwXHuhtcfafokSX1C25zTnmc8ZXkJhWpjUjTiNzKUN7Yryj5EurpucCI2BOE5s4C/mcD3UD9Jq28Zebip6yrWB+qqeXNcG6MZ5uW4jlOZP0vHfbnnhvkEfJsEKkHrxnG4PezVAZxkPSyx6Dd2IIPuJDK4FvaJweupGlPvHrdIorn6E8EQuT+d0S+59gaKDd4ca0EB5lbXgnxtBn4P/zJs789vfhZuSSEh2PH7cRCiIRJJoI6H8ZADtaBxEZVTtgPfUZu/iSePP6JHlXyvX07bSIX1YAepKVlsg7YYnzNgYl4RZ6Xlpw8Qg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
