travis:
  secure:
    BINSTAR_TOKEN: WDstvmrThAA7pRMd/mffW1b2oVu3DjFlReK9SLXLOuZC+F/XaiIVMYcUE90DApXHkc2vGaYCZZYrXCtODW7gYeAq/JdncmvAB+ci1FpONhu/aTfzGTeLH+qyKDecUnM4CJUrxJFVlr4GJ4NJDKwufA/YBWNbIoc07zqPHb5c9rpxbo868UG7gnvcVqZCUsqq36lSRLGuUUp2eilEzrJzZnNiLhTSuQ2DQ/pz4126MKVt3tP/v6oFSmsZ18wNNUbPLq3cjUmwjhptKPTU8MXKJCIb4BLehHJwjTsn7utatzyjEvXHu4m590DKg+SVFhfZwcTOR931Si3rO914jKoy8PQbCWUOung+paeU0ZHVTh8ETmLa5uY/rPVwvhP3t9CxB3jna6CVaQ3h6l3WM5wE6nuREvvf/nkzZRZMbCj3dVtp9Dmh8LvCSLmQoHt17RMqz4+t+aMromeOp2plU5PDCkYzmOdla8pV3HPURdr6ejfwTI/l7TnNAmObmGNABAHTQqNv/iQqWbfGqlpi45N7UPkSRiCzDCV3VHLhyiiAqFfsfddZolIOotEP76OjzrwXH3bueaYdI37ljJHXGbYgl0taLi0EQoVcrcJ/lgw3u2lsz0h3A/DoPAi2x6SBh+l6VWPCRRFwcypuaaCDRiaBwlWP3bVrcGRk8f94xxsSkQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
